kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql
  namespace: rhoai-model-registries
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: mysql
    component: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: rhoai-model-registries
spec:
  ports:
    - name: mysql
      nodePort: 0
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: rhoai-model-registries
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
      containers:
        - envFrom:
          - secretRef:
              name: myregistry-mysql
          args:
            - --datadir
            - /var/lib/mysql/datadir
          image: "mysql:8.3.0"
          imagePullPolicy: IfNotPresent
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "500m"
              memory: 1Gi
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
