apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: myregistry
  name: myregistry
  namespace: rhoai-model-registries
  finalizers:
    - modelregistry.opendatahub.io/finalizer
spec:
  grpc:
    port: 9090
  mysql:
    database: registry
    host: mysql.rhoai-model-registries.svc.cluster.local
    passwordSecret:
      key: database-password
      name: myregistry-registry
    port: 3306
    skipDBCreation: false
    username: myuser
  kubeRBACProxy:
    port: 8443
    routePort: 443
    serviceRoute: enabled
  rest:
    port: 8080
    serviceRoute: disabled